plugins {
    id 'com.github.johnrengelman.shadow' apply false
}

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

allprojects {
    group 'org.example'
    version '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    sourceCompatibility = '17'
    targetCompatibility = '17'

    group 'org.example'
    version '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation 'moniq:moniq'

        implementation 'org.apache.kafka:kafka-clients:3.9.1'
        implementation 'org.slf4j:slf4j-api:2.0.7'
        runtimeOnly 'org.apache.logging.log4j:log4j-slf4j2-impl:2.24.3'
        implementation 'org.apache.poi:poi-ooxml:5.4.0'

        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    }

    plugins.withId('com.github.johnrengelman.shadow') {
        tasks.withType(ShadowJar).tap {
            configureEach {
                destinationDirectory = file("$rootDir/build/libs")
                archiveBaseName = project.path.substring(1).replace(':', '.')
            }
        }
    }

    test {
        useJUnitPlatform()
    }

    tasks.named('clean', Delete) {
        delete "$rootDir/build"
    }
}
